import type { NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import styles from "./index.module.scss";
import { motion } from "framer-motion";
import variants from "./index.motion";

// Type definitions provided by next
import { GetServerSideProps } from "next";

// Components
import Heading from "@components/atoms/Heading/Heading";
import Featured from "@components/templates/Featured";

// This gets called on every request
export const getServerSideProps: GetServerSideProps = async () => {
  // Fetch data from external API
  // https://dummyjson.com/
  const res = await fetch(`https://dummyjson.com/posts`);
  const data = await res.json();
  // Pass data to the page via props
  return {
    props: { data },
  };
};

interface Properties {
  [key: string]: any;
  id?: number;
  title?: string;
  body?: string;
  userId?: number;
  tags?: number;
  reactions?: number;
}

const HomePage: NextPage<Properties> = (props) => {
  const { posts } = props.data;

  return (
    <div className={styles.container}>
      <Head>
        <title>Headstart Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <motion.div
          className={styles.title}
          variants={variants.bg}
          initial={"initial"}
          animate={"in"}
          exit={"out"}
        >
          <motion.div variants={variants.title}>
            <Heading size={1}>A Next.js Starter File.</Heading>
            <p>
              Configured for{" "}
              <a href="https://github.com/css-modules/css-modules">
                SCSS Modules
              </a>
              , <a href="https://storybook.js.org/"> StoryBoard</a>,
              <a href="https://jestjs.io/"> Jest</a>,
              <a href="https://playwright.dev/"> Playwright.js </a>
              and <a href="https://www.framer.com/motion/">Framer-Motion.</a>
            </p>
          </motion.div>
        </motion.div>
        <Featured heading={"Featured posts"} posts={posts} limit={6} />
        <div className={styles.spacer}></div>
      </main>
    </div>
  );
};

export default HomePage;
